export { default as SimpleCentered } from './simple-centered'
export { default as SplitWithImage } from './split-with-image'
export { SplitWithScreenshot } from './split-with-screenshot'
export { default as SplitWithScreenshotDark } from './split-with-screenshot-dark'
export { SplitWithCodeExample } from './split-with-code-example'
export { SimpleCenteredWithBackgroundImage } from './simple-centered-with-background-image'
export { WithAppScreenshot } from './with-app-screenshot'
export { WithAppScreenshotOnDark } from './with-app-screenshot-on-dark'
export { WithPhoneMockup } from './with-phone-mockup'
export { WithAngledImageOnRight } from './with-angled-image-on-right'
export { WithImageTiles } from './with-image-tiles'
export { WithOffsetImage } from './with-offset-image'
